#!/bin/sh
#-----------------------------------------------------------------------
# paco2porg - imports paco logs into a porg database.
#-----------------------------------------------------------------------
# This file is part of the package porg
# Copyright (C) 2014 David Ricart
# For more information visit http://porg.sourceforge.net
#----------------------------------------------------------------------

me=$(basename $0)


help()
{
cat << EOF
$me - imports paco logs into a porg database.

Usage:
  $me [OPTIONS]

Options:
  -h, --help       Display this usage message and exit.
  -V, --version    Display version information and exit.
  -v, --verbose    Explain what is being done.

EOF
	exit 0
}

# Parse the command line

while [ "$1" ]; do
	case $1 in
		-v|--verbose) verb=yes;;
		-V|--version) porg -V | sed "s@^porg@$me@"; exit 0;;
		*)	help;;
	esac
	shift
done

# Process the packages

for pkg in $(paco -av); do
	[ "$verb" ] && echo -n "Importing package ${pkg}...\t"
	( paco -zf $pkg | porg -lmp $pkg ) && [ "$verb" ] && echo "done"
done

exit 0

